// This file is auto-generated by scripts/generate-property-metadata.ts
// Do not edit manually

import { registerGeneratedClassMetadata, registerGeneratedPropertyMetadata } from '@gnsx/genesys.js';

import { DynamicUVNodeMaterialAsset } from './dynamic-uv-material.js';
import { PlayerAnimationSettingsComponent } from './animation/PlayerAnimationSettingsComponent.js';
import { SideScrollCameraComponent } from './camera/SideScrollCameraComponent.js';
import { AttackComponent } from './combat/AttackComponent.js';
import { EquippedWeaponComponent } from './combat/EquippedWeaponComponent.js';
import { EnemyActor } from './enemy/EnemyActor.js';
import { CombatFeelSettingsComponent } from './feel/CombatFeelSettingsComponent.js';
import { SoundFeedbackSettingsComponent } from './feel/SoundFeedbackSettingsComponent.js';
import { CheckpointActor } from './gameplay/CheckpointActor.js';
import { ExitActor } from './gameplay/ExitActor.js';
import { HealthPickupActor } from './gameplay/HealthPickupActor.js';
import { PlatformerMovementSettingsComponent } from './movement/PlatformerMovementSettingsComponent.js';
import { PlayerHealthComponent } from './player/PlayerHealthComponent.js';
import { SlimeCameraNode } from './slime/SlimeCameraNode.js';
import { SlimeMovementSettingsNode } from './slime/SlimeMovement.js';
import { SlimeMassNode } from './slime/SlimePawn.js';
import { BiomassPickupNode, PrototypeExitNode, SlimeAnchorNode, SlimeMassGateNode } from './slime/SlimeWorldNodes.js';

export function registerMetadata(): void {
  registerGeneratedClassMetadata(DynamicUVNodeMaterialAsset, { description: "World-space triplanar material. Samples the texture three times using\nworld-position XZ, XY, and YZ planes, then blends by the world normal —\nno per-mesh UV coordinates required." });
  registerGeneratedPropertyMetadata(DynamicUVNodeMaterialAsset, {
      "mapPath": {
        "type": "texturePath",
        "description": "Base color texture"
      },
      "scale": {
        "type": "number",
        "min": 0.01,
        "max": 20,
        "step": 0.01,
        "description": "Texture scale in world units"
      },
      "color": {
        "type": "color",
        "description": "Tint color"
      },
      "roughness": {
        "type": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Roughness"
      },
      "metalness": {
        "type": "number",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Metalness"
      }
    });

  registerGeneratedPropertyMetadata(PlayerAnimationSettingsComponent, {
      "moveThreshold": {
        "type": "number",
        "category": "Animation",
        "min": 0,
        "max": 0.5,
        "step": 0.01,
        "description": "Normalized speed above which the character counts as moving."
      },
      "idleBreakDelaySeconds": {
        "type": "number",
        "category": "Animation",
        "min": 0,
        "max": 30,
        "step": 0.5,
        "description": "Seconds standing still before an idle-break clip plays."
      },
      "hardLandingSpeed": {
        "type": "number",
        "category": "Animation",
        "min": 1,
        "max": 60,
        "step": 0.5,
        "description": "Downward impact speed (units/s) that picks the heavy land clip."
      },
      "airBlendRange": {
        "type": "number",
        "category": "Animation",
        "min": 1,
        "max": 40,
        "step": 0.5,
        "description": "Vertical-speed magnitude (units/s) mapped across the air rise/fall blend."
      },
      "takeoffTimeoutSeconds": {
        "type": "number",
        "category": "Animation",
        "min": 0.1,
        "max": 2,
        "step": 0.05,
        "description": "Safety timeout (s): force air loop if take-off clip never finishes."
      },
      "landingTimeoutSeconds": {
        "type": "number",
        "category": "Animation",
        "min": 0.1,
        "max": 2,
        "step": 0.05,
        "description": "Safety timeout (s): leave land state if its clip never finishes."
      },
      "damageTimeoutSeconds": {
        "type": "number",
        "category": "Animation",
        "min": 0.1,
        "max": 2,
        "step": 0.05,
        "description": "Safety timeout (s): leave damage state if its clip never finishes."
      },
      "attackPlaybackSpeed": {
        "type": "number",
        "category": "Attack Anim",
        "min": 0.25,
        "max": 4,
        "step": 0.05,
        "description": "Playback rate of SwordSlash (also scales melee hit windows)."
      },
      "attackTimeoutSeconds": {
        "type": "number",
        "category": "Attack Anim",
        "min": 0.1,
        "max": 2,
        "step": 0.05,
        "description": "Safety timeout (s): leave attack state if SwordSlash never finishes."
      }
    });

  registerGeneratedPropertyMetadata(SideScrollCameraComponent, {
      "camera": {
        "type": "unknown",
        "hidden": true
      },
      "distance": {
        "type": "number",
        "category": "Camera",
        "min": 2,
        "max": 80,
        "step": 0.5,
        "description": "Distance from the play plane along +Z (units)."
      },
      "offsetY": {
        "type": "number",
        "category": "Camera",
        "min": -5,
        "max": 10,
        "step": 0.1,
        "description": "Vertical offset added to the follow target so the character sits lower on screen."
      },
      "followLambdaX": {
        "type": "number",
        "category": "Camera",
        "min": 0.5,
        "max": 30,
        "step": 0.1,
        "description": "Horizontal follow responsiveness (higher = snappier)."
      },
      "followLambdaY": {
        "type": "number",
        "category": "Camera",
        "min": 0.5,
        "max": 30,
        "step": 0.1,
        "description": "Vertical follow responsiveness (higher = snappier; usually softer than X)."
      },
      "verticalDeadzone": {
        "type": "number",
        "category": "Camera",
        "min": 0,
        "max": 8,
        "step": 0.1,
        "description": "Half-height of the vertical dead-zone; camera only tracks Y past this band."
      },
      "fov": {
        "type": "number",
        "category": "Camera",
        "min": 20,
        "max": 90,
        "step": 1,
        "description": "Perspective field of view in degrees."
      }
    });

  registerGeneratedPropertyMetadata(AttackComponent, {
      "damage": {
        "type": "number",
        "category": "Melee",
        "min": 0,
        "max": 200,
        "step": 1,
        "description": "Damage dealt per successful swing."
      },
      "cooldown": {
        "type": "number",
        "category": "Melee",
        "min": 0,
        "max": 2,
        "step": 0.01,
        "description": "Extra wait after recovery before another swing can start (seconds)."
      },
      "reach": {
        "type": "number",
        "category": "Hitbox",
        "min": 0.1,
        "max": 3,
        "step": 0.05,
        "description": "Distance from character center to hitbox center along facing (units)."
      },
      "hitboxHalfWidth": {
        "type": "number",
        "category": "Hitbox",
        "min": 0.1,
        "max": 3,
        "step": 0.05,
        "description": "Half-width of the attack trigger box (units)."
      },
      "hitboxHalfHeight": {
        "type": "number",
        "category": "Hitbox",
        "min": 0.1,
        "max": 3,
        "step": 0.05,
        "description": "Half-height of the attack trigger box (units)."
      },
      "hitboxOffsetY": {
        "type": "number",
        "category": "Hitbox",
        "min": -2,
        "max": 2,
        "step": 0.05,
        "description": "Vertical offset of the hitbox center (units)."
      },
      "startup": {
        "type": "number",
        "category": "Timing",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Wind-up before the hitbox arms, at 1× attack anim speed (seconds)."
      },
      "active": {
        "type": "number",
        "category": "Timing",
        "min": 0.01,
        "max": 1,
        "step": 0.01,
        "description": "How long the hitbox stays armed, at 1× attack anim speed (seconds)."
      },
      "recovery": {
        "type": "number",
        "category": "Timing",
        "min": 0,
        "max": 1.5,
        "step": 0.01,
        "description": "Follow-through after the hitbox disarms on a miss, at 1× anim speed (seconds)."
      },
      "cancelOnHit": {
        "type": "boolean",
        "category": "Hit Cancel",
        "description": "On first connect, shorten recovery so the next attack can start sooner."
      },
      "hitCancelRecovery": {
        "type": "number",
        "category": "Hit Cancel",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Short rooted follow-through after a connect before unlocking (seconds)."
      },
      "hitCancelCooldown": {
        "type": "number",
        "category": "Hit Cancel",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Cooldown after a hit-cancel (usually shorter than a full miss cooldown)."
      }
    });

  registerGeneratedPropertyMetadata(EquippedWeaponComponent, {
      "modelUrl": {
        "type": "modelPath",
        "category": "Weapon",
        "description": "Weapon GLB path (@project / @engine)."
      },
      "hostMeshName": {
        "type": "string",
        "category": "Weapon",
        "description": "Name of the host ModelMeshComponent to socket onto."
      },
      "socketName": {
        "type": "string",
        "category": "Socket",
        "description": "Logical socket name created on the host mesh."
      },
      "boneName": {
        "type": "string",
        "category": "Socket",
        "description": "Skeleton bone to bind the socket to (Mixamo: mixamorigRightHand)."
      },
      "socketOffset": {
        "type": "vector3",
        "category": "Socket",
        "description": "Socket offset relative to the bone."
      },
      "socketRotation": {
        "type": "euler",
        "category": "Socket",
        "description": "Socket rotation relative to the bone."
      },
      "socketScale": {
        "type": "vector3",
        "category": "Socket",
        "description": "Socket scale relative to the bone."
      },
      "localOffset": {
        "type": "vector3",
        "category": "Mesh",
        "description": "Extra local position of the weapon under the socket."
      },
      "localRotation": {
        "type": "euler",
        "category": "Mesh",
        "description": "Extra local rotation of the weapon under the socket."
      },
      "localScale": {
        "type": "vector3",
        "category": "Mesh",
        "description": "Extra local scale of the weapon under the socket."
      },
      "driveAttackAnimation": {
        "type": "boolean",
        "category": "Weapon",
        "description": "Play the attack graph state when attackStart feedback fires."
      }
    });

  registerGeneratedPropertyMetadata(EnemyActor, {
      "maxHealth": {
        "type": "number",
        "category": "Combat",
        "min": 1,
        "max": 500,
        "step": 1,
        "description": "Maximum hit points for this enemy."
      },
      "contactDamage": {
        "type": "number",
        "category": "Combat",
        "min": 0,
        "max": 200,
        "step": 1,
        "description": "Damage dealt to the player on body contact each tick while overlapping."
      },
      "moveSpeed": {
        "type": "number",
        "category": "Patrol",
        "min": 0,
        "max": 20,
        "step": 0.1,
        "description": "Horizontal patrol speed (units/s)."
      },
      "patrolRange": {
        "type": "number",
        "category": "Patrol",
        "min": 0,
        "max": 30,
        "step": 0.1,
        "description": "Half-width of the patrol span from spawn X (units)."
      },
      "hitStunDuration": {
        "type": "number",
        "category": "Hit Reaction",
        "min": 0,
        "max": 2,
        "step": 0.05,
        "description": "Seconds patrol freezes after taking damage (0 disables)."
      },
      "knockbackDistance": {
        "type": "number",
        "category": "Hit Reaction",
        "min": 0,
        "max": 3,
        "step": 0.05,
        "description": "World units shoved away from the player on hit (0 disables)."
      },
      "knockbackDuration": {
        "type": "number",
        "category": "Hit Reaction",
        "min": 0.05,
        "max": 1,
        "step": 0.01,
        "description": "Seconds over which knockback distance is applied."
      },
      "corpseLingerDuration": {
        "type": "number",
        "category": "Death",
        "min": 0,
        "max": 5,
        "step": 0.05,
        "description": "Seconds the corpse stays after the death clip before despawning."
      },
      "despawnFadeDuration": {
        "type": "number",
        "category": "Death",
        "min": 0.05,
        "max": 2,
        "step": 0.05,
        "description": "Seconds to shrink the mesh during despawn."
      },
      "deathVfxEnabled": {
        "type": "boolean",
        "category": "Death",
        "description": "Play a particle burst when the corpse despawns."
      },
      "deathVfxPath": {
        "type": "vfxPath",
        "category": "Death",
        "description": "VFX JSON path for the despawn burst (@project / @engine)."
      }
    });

  registerGeneratedPropertyMetadata(CombatFeelSettingsComponent, {
      "attackHitStop": {
        "type": "number",
        "category": "Hit Stop",
        "min": 0,
        "max": 0.5,
        "step": 0.005,
        "description": "Hit-stop duration (s) when a melee swing connects."
      },
      "playerDamageHitStop": {
        "type": "number",
        "category": "Hit Stop",
        "min": 0,
        "max": 0.5,
        "step": 0.005,
        "description": "Hit-stop duration (s) when the player takes damage."
      },
      "enemyDeathHitStop": {
        "type": "number",
        "category": "Hit Stop",
        "min": 0,
        "max": 0.5,
        "step": 0.005,
        "description": "Hit-stop duration (s) when an enemy dies."
      },
      "playerDeathHitStop": {
        "type": "number",
        "category": "Hit Stop",
        "min": 0,
        "max": 0.5,
        "step": 0.005,
        "description": "Hit-stop duration (s) when the player dies."
      },
      "attackHitShakeAmplitude": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake amplitude on melee connect."
      },
      "attackHitShakeDuration": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake duration (s) on melee connect."
      },
      "playerDamageShakeAmplitude": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake amplitude when the player takes damage."
      },
      "playerDamageShakeDuration": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake duration (s) when the player takes damage."
      },
      "enemyDeathShakeAmplitude": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake amplitude when an enemy dies."
      },
      "enemyDeathShakeDuration": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake duration (s) when an enemy dies."
      },
      "playerDeathShakeAmplitude": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake amplitude when the player dies."
      },
      "playerDeathShakeDuration": {
        "type": "number",
        "category": "Camera Shake",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Camera shake duration (s) when the player dies."
      },
      "hitSparkVfxPath": {
        "type": "vfxPath",
        "category": "Hit Spark",
        "description": "VFX JSON path for the impact spark (@project / @engine)."
      },
      "hitSparkScale": {
        "type": "number",
        "category": "Hit Spark",
        "min": 0.1,
        "max": 5,
        "step": 0.05,
        "description": "Uniform scale of the hit-spark VFX."
      }
    });

  registerGeneratedPropertyMetadata(SoundFeedbackSettingsComponent, {
      "footstepPath": {
        "type": "audioPath",
        "category": "Movement",
        "description": "Sound played for each animation-driven footstep."
      },
      "footstepVolume": {
        "type": "number",
        "category": "Movement",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Footstep sound volume."
      },
      "jumpPath": {
        "type": "audioPath",
        "category": "Movement",
        "description": "Sound played when the player jumps."
      },
      "jumpVolume": {
        "type": "number",
        "category": "Movement",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Jump sound volume."
      },
      "landPath": {
        "type": "audioPath",
        "category": "Movement",
        "description": "Sound played when the player lands."
      },
      "landVolume": {
        "type": "number",
        "category": "Movement",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Landing sound volume."
      },
      "swordSwingPath": {
        "type": "audioPath",
        "category": "Player Combat",
        "description": "Sound played when a melee attack starts."
      },
      "swordSwingVolume": {
        "type": "number",
        "category": "Player Combat",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Melee swing sound volume."
      },
      "swordHitPath": {
        "type": "audioPath",
        "category": "Player Combat",
        "description": "Sound played when a melee attack connects."
      },
      "swordHitVolume": {
        "type": "number",
        "category": "Player Combat",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Melee hit sound volume."
      },
      "playerHurtPath": {
        "type": "audioPath",
        "category": "Player Combat",
        "description": "Sound played when the player takes damage."
      },
      "playerHurtVolume": {
        "type": "number",
        "category": "Player Combat",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Player hurt sound volume."
      },
      "playerDeathPath": {
        "type": "audioPath",
        "category": "Player Combat",
        "description": "Sound played when the player dies."
      },
      "playerDeathVolume": {
        "type": "number",
        "category": "Player Combat",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Player death sound volume."
      },
      "enemyAttackPath": {
        "type": "audioPath",
        "category": "Enemy",
        "description": "Sound played when an enemy attacks."
      },
      "enemyAttackVolume": {
        "type": "number",
        "category": "Enemy",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Enemy attack sound volume."
      },
      "enemyHurtPath": {
        "type": "audioPath",
        "category": "Enemy",
        "description": "Sound played when an enemy takes damage."
      },
      "enemyHurtVolume": {
        "type": "number",
        "category": "Enemy",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Enemy hurt sound volume."
      },
      "enemyDeathPath": {
        "type": "audioPath",
        "category": "Enemy",
        "description": "Sound played when an enemy dies."
      },
      "enemyDeathVolume": {
        "type": "number",
        "category": "Enemy",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Enemy death sound volume."
      },
      "despawnPath": {
        "type": "audioPath",
        "category": "World",
        "description": "Sound played when an actor despawns."
      },
      "despawnVolume": {
        "type": "number",
        "category": "World",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Despawn sound volume."
      },
      "pickupPath": {
        "type": "audioPath",
        "category": "World",
        "description": "Sound played when the player collects a pickup."
      },
      "pickupVolume": {
        "type": "number",
        "category": "World",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Pickup sound volume."
      },
      "checkpointPath": {
        "type": "audioPath",
        "category": "World",
        "description": "Sound played when a checkpoint activates."
      },
      "checkpointVolume": {
        "type": "number",
        "category": "World",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Checkpoint sound volume."
      },
      "levelCompletePath": {
        "type": "audioPath",
        "category": "World",
        "description": "Sound played when the level is completed."
      },
      "levelCompleteVolume": {
        "type": "number",
        "category": "World",
        "min": 0,
        "max": 1,
        "step": 0.05,
        "description": "Level-complete sound volume."
      }
    });

  registerGeneratedPropertyMetadata(CheckpointActor, {
      "radius": {
        "type": "number",
        "category": "Proximity",
        "min": 0.1,
        "max": 20,
        "step": 0.1,
        "description": "Distance from this actor at which the player triggers the checkpoint (units)."
      }
    });

  registerGeneratedPropertyMetadata(ExitActor, {
      "radius": {
        "type": "number",
        "category": "Proximity",
        "min": 0.1,
        "max": 20,
        "step": 0.1,
        "description": "Distance from the open exit at which the player completes the level (units)."
      }
    });

  registerGeneratedPropertyMetadata(HealthPickupActor, {
      "radius": {
        "type": "number",
        "category": "Proximity",
        "min": 0.1,
        "max": 20,
        "step": 0.1,
        "description": "Distance from this actor at which the player collects the pickup (units)."
      }
    });

  registerGeneratedPropertyMetadata(PlatformerMovementSettingsComponent, {
      "moveSpeed": {
        "type": "number",
        "category": "Movement",
        "min": 0.5,
        "max": 20,
        "step": 0.1,
        "description": "Max horizontal speed (units/s)."
      },
      "acceleration": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 200,
        "step": 1,
        "description": "How fast speed ramps toward moveSpeed on ground (units/s²)."
      },
      "deceleration": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 200,
        "step": 1,
        "description": "How fast the character brakes with no input (units/s²)."
      },
      "jumpForce": {
        "type": "number",
        "category": "Jump",
        "min": 1,
        "max": 40,
        "step": 0.1,
        "description": "Initial upward velocity on jump (units/s)."
      },
      "jumpCutMultiplier": {
        "type": "number",
        "category": "Jump",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Multiplier on upward velocity when jump is released early (variable jump height)."
      },
      "gravity": {
        "type": "number",
        "category": "Jump",
        "min": 1,
        "max": 100,
        "step": 0.5,
        "description": "Downward acceleration while rising (units/s²)."
      },
      "fallGravity": {
        "type": "number",
        "category": "Jump",
        "min": 1,
        "max": 120,
        "step": 0.5,
        "description": "Downward acceleration while falling (higher = snappier fall)."
      },
      "maxFallSpeed": {
        "type": "number",
        "category": "Jump",
        "min": 1,
        "max": 80,
        "step": 0.5,
        "description": "Terminal fall speed (units/s)."
      },
      "coyoteTime": {
        "type": "number",
        "category": "Jump",
        "min": 0,
        "max": 0.5,
        "step": 0.01,
        "description": "Seconds after leaving a ledge where jump still works (coyote time)."
      },
      "jumpBufferTime": {
        "type": "number",
        "category": "Jump",
        "min": 0,
        "max": 0.5,
        "step": 0.01,
        "description": "Seconds a jump press is remembered before landing (jump buffer)."
      },
      "airControl": {
        "type": "number",
        "category": "Air",
        "min": 0,
        "max": 1,
        "step": 0.01,
        "description": "Fraction of ground accel/decel available in air (0 = none, 1 = full)."
      }
    });

  registerGeneratedPropertyMetadata(PlayerHealthComponent, {
      "invulnDuration": {
        "type": "number",
        "category": "Health",
        "min": 0,
        "max": 5,
        "step": 0.05,
        "description": "Seconds of invulnerability frames after taking a hit (0 disables)."
      },
      "knockbackDistance": {
        "type": "number",
        "category": "Hit Reaction",
        "min": 0,
        "max": 3,
        "step": 0.05,
        "description": "World units shoved away from the attacker along facing on hit (0 disables)."
      },
      "knockbackDuration": {
        "type": "number",
        "category": "Hit Reaction",
        "min": 0.05,
        "max": 1,
        "step": 0.01,
        "description": "Seconds over which knockback distance is applied."
      }
    });

  registerGeneratedPropertyMetadata(SlimeCameraNode, {
      "camera": {
        "type": "unknown",
        "hidden": true
      },
      "distance": {
        "type": "number",
        "category": "Camera",
        "min": 8,
        "max": 50,
        "step": 0.5
      },
      "offsetY": {
        "type": "number",
        "category": "Camera",
        "min": -5,
        "max": 10,
        "step": 0.1
      },
      "followLambda": {
        "type": "number",
        "category": "Camera",
        "min": 0.5,
        "max": 30,
        "step": 0.1
      }
    });

  registerGeneratedPropertyMetadata(SlimeMovementSettingsNode, {
      "smallSpeed": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 20,
        "step": 0.1
      },
      "mediumSpeed": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 20,
        "step": 0.1
      },
      "largeSpeed": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 20,
        "step": 0.1
      },
      "acceleration": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 200,
        "step": 1
      },
      "airControl": {
        "type": "number",
        "category": "Movement",
        "min": 0,
        "max": 1,
        "step": 0.05
      },
      "gravity": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 100,
        "step": 1
      },
      "maxFallSpeed": {
        "type": "number",
        "category": "Movement",
        "min": 1,
        "max": 100,
        "step": 1
      },
      "tetherPull": {
        "type": "number",
        "category": "Stretch",
        "min": 1,
        "max": 100,
        "step": 1
      },
      "swingAcceleration": {
        "type": "number",
        "category": "Stretch",
        "min": 0,
        "max": 60,
        "step": 1
      },
      "releaseBoost": {
        "type": "number",
        "category": "Stretch",
        "min": 0,
        "max": 20,
        "step": 0.25
      }
    });

  registerGeneratedPropertyMetadata(SlimeMassNode, {
      "initialOriginalMass": {
        "type": "number",
        "category": "Mass",
        "min": 20,
        "max": 500,
        "step": 1
      },
      "minimumControlledMass": {
        "type": "number",
        "category": "Mass",
        "min": 1,
        "max": 100,
        "step": 1
      },
      "minimumPieceMass": {
        "type": "number",
        "category": "Mass",
        "min": 1,
        "max": 20,
        "step": 1
      },
      "maximumDetachedPieces": {
        "type": "number",
        "category": "Mass",
        "min": 1,
        "max": 12,
        "step": 1
      },
      "splitChargeDuration": {
        "type": "number",
        "category": "Mass",
        "min": 0.2,
        "max": 3,
        "step": 0.1
      }
    });

  registerGeneratedPropertyMetadata(SlimeAnchorNode, {
      "activationRadius": {
        "type": "number",
        "category": "Anchor",
        "min": 2,
        "max": 20,
        "step": 0.25
      }
    });

  registerGeneratedPropertyMetadata(BiomassPickupNode, {
      "massValue": {
        "type": "number",
        "category": "Biomass",
        "min": 1,
        "max": 200,
        "step": 1
      }
    });

  registerGeneratedPropertyMetadata(SlimeMassGateNode, {
      "openHeight": {
        "type": "number",
        "category": "Gate",
        "min": 1,
        "max": 12,
        "step": 0.25
      },
      "openSpeed": {
        "type": "number",
        "category": "Gate",
        "min": 0.25,
        "max": 8,
        "step": 0.25
      }
    });

  registerGeneratedPropertyMetadata(PrototypeExitNode, {
      "requiredMass": {
        "type": "number",
        "category": "Exit",
        "min": 1,
        "max": 500,
        "step": 1
      }
    });

}

// Deferred to avoid circular reference issues during module initialization
queueMicrotask(registerMetadata);
